project:
  type: website
  output-dir: docs

website:
  title: "Isaias Ghezae"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: https://www.dropbox.com/s/ba1m79dtsnom4no/Ghezae_CV.pdf?dl=0
        text: CV
      - href: work.qmd
        text: Academic Work
format:
  html:
    theme: [darkly, theme_dark_custom.scss] 
    # alternative theming -- dark: [darkly, theme_dark_custom.scss] light: [flatly, theme_light_custom.scss]
    css: styles.css

editor: visual










