project:
  type: website
  output-dir: docs

website:
  title: "Isaias Ghezae"
  favicon: images/favicon.png
  navbar:
    left:
      - href: cv.qmd
        text: CV
      - href: work.qmd
        text: Academic Work
    right:
      - icon: github
        href: https://github.com/isaiasghezae
      - icon: twitter
        href: https://twitter.com/ghezae_isaias
      - icon: envelope
        href: mailto:ighezae@stanford.edu
      
format:
  html:
    theme: 
      light: [flatly, theme_light_custom.scss] 
    # alternative theming -- dark: [darkly, theme_dark_custom.scss] light: [flatly, theme_light_custom.scss]
    css:
      - custom.css
      - styles.css
      
editor: visual










